/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guı_app;

/**
 *
 * @author HP
 */
public class FİrstApp5 extends javax.swing.JFrame {

    /**
     * Creates new form FİrstApp5
     */
    public FİrstApp5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ekran = new javax.swing.JLabel();
        cb_yazilim = new javax.swing.JCheckBox();
        cb_bilgisayar = new javax.swing.JCheckBox();
        cb_yapayzeka = new javax.swing.JCheckBox();
        cb_bilisim = new javax.swing.JCheckBox();
        btn_görüntüle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_ekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cb_yazilim.setText("Yazılım");
        cb_yazilim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_yazilimActionPerformed(evt);
            }
        });

        cb_bilgisayar.setText("Bilgisayar");
        cb_bilgisayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bilgisayarActionPerformed(evt);
            }
        });

        cb_yapayzeka.setText("Yapay Zeka");
        cb_yapayzeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_yapayzekaActionPerformed(evt);
            }
        });

        cb_bilisim.setText("Bilişim Sistemleri");
        cb_bilisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bilisimActionPerformed(evt);
            }
        });

        btn_görüntüle.setText("Görüntüle");
        btn_görüntüle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_görüntüleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_yazilim)
                                    .addComponent(cb_yapayzeka))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_bilisim)
                                    .addComponent(cb_bilgisayar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_görüntüle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_yazilim)
                    .addComponent(cb_bilgisayar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_yapayzeka)
                    .addComponent(cb_bilisim))
                .addGap(18, 18, 18)
                .addComponent(btn_görüntüle)
                .addGap(0, 119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_görüntüleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_görüntüleActionPerformed
     String metin = "";
        if(cb_yazilim.isSelected()){
            metin += cb_yazilim.getText() + ", ";
            
        }
       if (cb_bilgisayar.isSelected()) {
            metin += cb_bilgisayar.getText() + ", ";
        }
       if (cb_yapayzeka.isSelected()){
            metin += cb_yapayzeka.getText() + ", ";
            
        }
       if(cb_bilisim.isSelected()){
            metin+= cb_bilisim.getText() + ", ";
        }
              lbl_ekran.setText(metin);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_görüntüleActionPerformed

    private void cb_yazilimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_yazilimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_yazilimActionPerformed

    private void cb_bilgisayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bilgisayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_bilgisayarActionPerformed

    private void cb_yapayzekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_yapayzekaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_yapayzekaActionPerformed

    private void cb_bilisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bilisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_bilisimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FİrstApp5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FİrstApp5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FİrstApp5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FİrstApp5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FİrstApp5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_görüntüle;
    private javax.swing.JCheckBox cb_bilgisayar;
    private javax.swing.JCheckBox cb_bilisim;
    private javax.swing.JCheckBox cb_yapayzeka;
    private javax.swing.JCheckBox cb_yazilim;
    private javax.swing.JLabel lbl_ekran;
    // End of variables declaration//GEN-END:variables
}
